version: '3.4'

services:
    sql-server-db:
        container_name: sql-server-db
        image: microsoft/mssql-server-linux:2017-latest
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "123789password"
            ACCEPT_EULA: "Y"

    todoapplication:
        image: ${DOCKER_REGISTRY-}todoapplication
        build:
          context: .
          dockerfile: TodoApplication/Dockerfile

    
